// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  footer_link_list: dynamic(() => import("./FooterLinkList")),
  menu_item: dynamic(() => import("./MenuItem")),
};
