// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about: dynamic(() => import("./About")),
  choose_your_path: dynamic(() => import("./ChooseYourPath")),
  contact: dynamic(() => import("./Contact")),
  cta: dynamic(() => import("./Cta")),
  features: dynamic(() => import("./Features")),
  gallery: dynamic(() => import("./Gallery")),
  hero: dynamic(() => import("./Hero")),
  image_description_card_section: dynamic(
    () => import("./ImageDescriptionCardSection"),
  ),
  logo_carousel: dynamic(() => import("./LogoCarousel")),
  our_team: dynamic(() => import("./OurTeam")),
  paginated_items: dynamic(() => import("./PaginatedItems")),
  questions: dynamic(() => import("./Questions")),
  rich_text: dynamic(() => import("./RichText")),
  testimonial: dynamic(() => import("./Testimonial")),
  villa_design: dynamic(() => import("./VillaDesign")),
  why_us: dynamic(() => import("./WhyUs")),
};
